Update rpm, migrate to clap and add source_date_epoch flag
cat-in-136/cargo-generate-rpm pull request #83
Opened 2023-06-02 17:29 UTC by newpavlov

While `clap`-based code is somewhat heavier than `getopts`, it's more powerful and results in cleaner and easier to maintain code.

This PR also fixes a bunch of Clippy warnings and introduces the `source-date-epoch` flag necessary for reproducible builds.

It depends on yet unreleased version of `rpm`.

I am not completely sure I got the extra metadata stuff correctly, so it's better to double check it.

Closes #82

2023-06-15 11:46 UTC, newpavlov commented
@cat-in-136 
I would appreciate if you will give feedback on this PR before I spend time on resolving the conflicts.

2023-06-18 14:58 UTC, cat-in-136 commented
To resolve #82, the prerequisite is that the next version of rpm-rs/rpm have been released so that the git path does not have to be written to the Cargo.toml dependency. Other than that, some trivial work is required, such as updating README.md. In other words, there is still some work to be done.

On the other hand, if you remove the "source_date_epoch flag" and "closes #82" from this PR / branch, it is thought to be almost ready to merge.

What you do with it is up to you. Because you are a committer of rpm-rs/rpm.

----

Your clap branch `cargo-generate-rpm` works differently between `cargo-generate-rpm` and `cargo generate-rpm`. You can see this in the behavior of `cargo-generate-rpm --help` and `cargo generate-rpm --help`.

Some other cargo subcommands actually have this behavior, but I'd like to stick with it for compatibility with previous behavior and because it works properly with `cargo tauri` (which uses clap).

2023-06-19 02:24 UTC, newpavlov commented
I guess `rpm v0.12` will be released only after rpm-rs/rpm#159 gets resolved, so it will take a bit of time.

>Your clap branch cargo-generate-rpm works differently between cargo-generate-rpm and cargo generate-rpm. 

Do you have suggestions how it can be fixed? Personally, I dislike the subcommand workaround as well, but I couldn't find an easy way to fix it.

2023-07-14 16:40 UTC, newpavlov commented
@cat-in-136 
`rpm v0.12` was published, so this PR is ready for review/merge.

2023-08-06 03:46 UTC, cat-in-136 commented
@newpavlov Can you check my review comment above?

2023-08-06 09:22 UTC, newpavlov commented
Do you mean the difference between calling `cargo-generate-rpm` and `cargo generate-rpm`? I think I've already fixed it. Or have I missed something?

2023-08-06 14:13 UTC, cat-in-136 requested changes

2023-08-06 14:15 UTC, cat-in-136 commented
I have already confirmed that the issue of `cargo-generate-rpm` and `cargo generate-rpm` is resolved in following code.

```rust
    let mut args = std::env::args();
    let args = if let Some("generate-rpm") = args.nth(1).as_deref() {
        let CargoWrapper::GenerateRpm(args) = CargoWrapper::parse();
        args
    } else {
        Cli::parse()
    };
```

2023-08-06 15:08 UTC, newpavlov commented on src/main.rs
> +fn main() -> Result<(), Error> {
Fixed. Now `main` simply checks return result and in case of error prints it using `Display` impl and exits with code 1.

2023-08-08 13:28 UTC, cat-in-136 approved these changes

2023-08-08 13:28 UTC, merged

2023-08-08 13:28 UTC, cat-in-136 commented
Thanks a lot.